defmodule Linx.NFT.GoldenTest do
  @moduledoc """
  Round-trip golden tests against a curated corpus of nft fixtures
  in `test/linx/nft/fixtures/*.nft`.

  For each fixture, two assertions:

    1. **Structural round-trip** — `parse → format → parse` and
       the two `%Ruleset{}` values must be `==`. Catches parser
       bugs (info dropped on the way in) AND formatter bugs
       (info dropped on the way out).
    2. **Output stability** — `format → parse → format` and the
       two formatted strings must be byte-identical. Future-
       proofing for the `mix format` plugin in N9: applying
       `format/1` twice must converge.

  ## Curated vs aspirational corpus

  This module is the **curated corpus**: every fixture exercises
  only features the compiler / formatter already support, so each
  is expected to round-trip strictly. Adding a new fixture means
  dropping a `.nft` file in `test/linx/nft/fixtures/` — both
  assertions kick in automatically on the next test run.

  The **aspirational corpus** — real-world configs taken
  unmodified from the internet — is not implemented here yet. As
  the compiler grows (long-tail constructs land per follow-up
  commit), we'll add a parallel test module that pulls fixtures
  like these and asserts they round-trip:

    * **Debian default** — the upstream
      `/etc/nftables.conf` shipped by the Debian `nftables`
      package: https://salsa.debian.org/pkg-netfilter-team/pkg-nftables/-/blob/master/files/nftables.conf
    * **Arch default** — same role, Arch packaging:
      https://gitlab.archlinux.org/archlinux/packaging/packages/nftables/-/blob/main/nftables.conf
    * **Kubernetes nftables-mode kube-proxy** — generated by
      sigs.k8s.io/knftables: https://github.com/kubernetes-sigs/knftables
    * **firewalld** — uses libnftables JSON internally but emits
      equivalent nft syntax: https://firewalld.org/
    * **nftables wiki sample rulesets** —
      https://wiki.nftables.org/wiki-nftables/index.php/Sample_ruleset_for_a_server
      and friends

  The features each of those depends on but we haven't shipped
  yet:

    * `limit rate N/sec` (rate-limiting expression)
    * `meta mark set` / `ct mark set` (meta/ct **setters** — we
      have the readers)
    * Named objects: `counter ctr { … }`, `quota q { … }`,
      `limit l { … }` at table level (referenced by rules via
      `counter name @ctr`)
    * Flowtables (`flowtable ft { … }` + `flow add @ft`)
    * Concatenated set/map keys (`type ipv4_addr . inet_service`)
    * `include "path"` directives at top level
    * `define name = value` substitution

  When a missing construct lands in `Linx.NFT.Compiler` /
  `Formatter`, drop the corresponding real-world fixture into a
  new aspirational test module and watch it go green.
  """

  use ExUnit.Case, async: true

  alias Linx.NFT
  alias Linx.Netfilter.Ruleset

  @fixtures_dir Path.expand("fixtures", __DIR__)
  @fixtures @fixtures_dir |> Path.join("*.nft") |> Path.wildcard() |> Enum.sort()

  # Re-run tests when any fixture file changes.
  for path <- @fixtures do
    @external_resource path
  end

  if @fixtures == [] do
    raise "no fixtures found under #{@fixtures_dir}/*.nft — did the directory move?"
  end

  for path <- @fixtures do
    basename = Path.basename(path)

    describe "fixture: #{basename}" do
      test "parses without error" do
        source = File.read!(unquote(path))

        case NFT.parse(source, file: unquote(path)) do
          {:ok, %Ruleset{}} -> :ok
          {:error, err} -> flunk("parse failed: #{Exception.message(err)}")
        end
      end

      test "round-trip: parse → format → parse → equal" do
        source = File.read!(unquote(path))
        {:ok, rs1} = NFT.parse(source, file: unquote(path))
        formatted = NFT.format(rs1)

        case NFT.parse(formatted, file: "<formatted: #{unquote(basename)}>") do
          {:ok, rs2} ->
            assert rs1 == rs2,
                   "round-trip mismatch in #{unquote(basename)}\n\n" <>
                     "formatted output was:\n#{formatted}"

          {:error, err} ->
            flunk(
              "re-parse of formatted output failed for #{unquote(basename)}:\n" <>
                Exception.message(err) <>
                "\n\nformatted output was:\n#{formatted}"
            )
        end
      end

      test "output stability: format → parse → format byte-identical" do
        source = File.read!(unquote(path))
        {:ok, rs1} = NFT.parse(source, file: unquote(path))
        formatted1 = NFT.format(rs1)

        {:ok, rs2} = NFT.parse(formatted1, file: "<formatted-1>")
        formatted2 = NFT.format(rs2)

        assert formatted1 == formatted2,
               "format/1 is not idempotent for #{unquote(basename)} — " <>
                 "applying it twice produces different output"
      end
    end
  end
end
